name: Build React app

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

env:
  VITE_ENVIRONMENT: production
  VITE_API_URL: /api/

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: ci

    - name: Build production bundle
      uses: borales/actions-yarn@v4
      with:
        cmd: build
